// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Accountfilter struct {
	ClientID             pgtype.Text    `json:"client_id"`
	Account              string         `json:"account"`
	Trader               pgtype.Text    `json:"trader"`
	CashBalanceBf        pgtype.Numeric `json:"cash_balance_bf"`
	CashBalance          pgtype.Numeric `json:"cash_balance"`
	EstTransCost         pgtype.Numeric `json:"est_trans_cost"`
	EquityRealizedPl     pgtype.Numeric `json:"equity_realized_pl"`
	EquityUnrealizedPl   pgtype.Numeric `json:"equity_unrealized_pl"`
	MarginRealizedPl     pgtype.Numeric `json:"margin_realized_pl"`
	MarginUnrealizedPl   pgtype.Numeric `json:"margin_unrealized_pl"`
	EstClosingCost       pgtype.Numeric `json:"est_closing_cost"`
	TransactionNotBooked pgtype.Numeric `json:"transaction_not_booked"`
	EquityOrder          pgtype.Numeric `json:"equity_order"`
	AccountValue         pgtype.Numeric `json:"account_value"`
	DepositWithdraw      pgtype.Numeric `json:"deposit_withdraw"`
	CollateralHaircut    pgtype.Numeric `json:"collateral_haircut"`
	EquityPositionValue  pgtype.Numeric `json:"equity_position_value"`
	MarginRequirement    pgtype.Numeric `json:"margin_requirement"`
	Currency             pgtype.Text    `json:"currency"`
	BuyLimit             pgtype.Numeric `json:"buy_limit"`
	SellLimit            pgtype.Numeric `json:"sell_limit"`
	BuyExposure          pgtype.Numeric `json:"buy_exposure"`
	SellExposure         pgtype.Numeric `json:"sell_exposure"`
	LoanLimit            pgtype.Numeric `json:"loan_limit"`
	MarginFactor         pgtype.Numeric `json:"margin_factor"`
	AuthorizedOrderType  pgtype.Int8    `json:"authorized_order_type"`
	CalcMode             pgtype.Text    `json:"calc_mode"`
	LimitMode            pgtype.Int4    `json:"limit_mode"`
	Action               pgtype.Text    `json:"action"`
	NettingMode          string         `json:"netting_mode"`
	MaxOrdQty            pgtype.Numeric `json:"max_ord_qty"`
	MaxOrdVal            pgtype.Numeric `json:"max_ord_val"`
	NoOfTransaction      int32          `json:"no_of_transaction"`
	TransactionInterval  int16          `json:"transaction_interval"`
	CreatedAt            time.Time      `json:"created_at"`
}

type Currency struct {
	CurrencyPair string             `json:"currency_pair"`
	Bid          pgtype.Numeric     `json:"bid"`
	Ask          pgtype.Numeric     `json:"ask"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Instrumentfilter struct {
	Product             string         `json:"product"`
	Exchange            string         `json:"exchange"`
	Instrument          string         `json:"instrument"`
	Underlying          pgtype.Text    `json:"underlying"`
	Filter              pgtype.Int4    `json:"filter"`
	MaxOrderQty         pgtype.Numeric `json:"max_order_qty"`
	MaxOrderPrice       pgtype.Numeric `json:"max_order_price"`
	MaxOrderValue       pgtype.Numeric `json:"max_order_value"`
	BuyLmt              pgtype.Numeric `json:"buy_lmt"`
	SellLmt             pgtype.Numeric `json:"sell_lmt"`
	ExposureFactor      pgtype.Numeric `json:"exposure_factor"`
	BuyExposure         pgtype.Numeric `json:"buy_exposure"`
	SellExposure        pgtype.Numeric `json:"sell_exposure"`
	BuyQtyLmt           pgtype.Numeric `json:"buy_qty_lmt"`
	BuyQtyExposure      pgtype.Numeric `json:"buy_qty_exposure"`
	SellQtyLmt          pgtype.Numeric `json:"sell_qty_lmt"`
	SellQtyExposure     pgtype.Numeric `json:"sell_qty_exposure"`
	NetQtyLmt           pgtype.Numeric `json:"net_qty_lmt"`
	NetQtyExposure      pgtype.Numeric `json:"net_qty_exposure"`
	MarginType          pgtype.Text    `json:"margin_type"`
	Im                  pgtype.Numeric `json:"im"`
	Mm                  pgtype.Numeric `json:"mm"`
	MarginableRatio     pgtype.Numeric `json:"marginable_ratio"`
	MarginCurr          pgtype.Text    `json:"margin_curr"`
	CommissionType      pgtype.Text    `json:"commission_type"`
	Commission          pgtype.Numeric `json:"commission"`
	MinCommission       pgtype.Numeric `json:"min_commission"`
	CommissionCurr      pgtype.Text    `json:"commission_curr"`
	AuthorizedOrderType pgtype.Int8    `json:"authorized_order_type"`
	TradingCurr         pgtype.Text    `json:"trading_curr"`
	PriceCode           pgtype.Text    `json:"price_code"`
	ActionOnRecord      int16          `json:"action_on_record"`
	RefPx               pgtype.Numeric `json:"ref_px"`
	RefPxType           pgtype.Int2    `json:"ref_px_type"`
	ContractSize        pgtype.Numeric `json:"contract_size"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Order struct {
	OrderID          string             `json:"order_id"`
	ClientID         string             `json:"client_id"`
	TradingAcct      string             `json:"trading_acct"`
	Exchange         string             `json:"exchange"`
	Product          string             `json:"product"`
	Instrument       string             `json:"instrument"`
	Side             pgtype.Text        `json:"side"`
	Status           pgtype.Text        `json:"status"`
	OrderType        pgtype.Text        `json:"order_type"`
	OrderQty         pgtype.Numeric     `json:"order_qty"`
	OrderPrice       pgtype.Numeric     `json:"order_price"`
	TimeInforce      pgtype.Text        `json:"time_inforce"`
	TradingSessionID pgtype.Text        `json:"trading_session_id"`
	ExpireDate       pgtype.Date        `json:"expire_date"`
	ExecQty          pgtype.Numeric     `json:"exec_qty"`
	ExecPrice        pgtype.Numeric     `json:"exec_price"`
	Cash             pgtype.Numeric     `json:"cash"`
	Im               pgtype.Numeric     `json:"im"`
	Exposure         pgtype.Numeric     `json:"exposure"`
	EstCostToClose   pgtype.Numeric     `json:"est_cost_to_close"`
	OrderTime        pgtype.Timestamptz `json:"order_time"`
	CreatedAt        time.Time          `json:"created_at"`
}

type Position struct {
	PositionID             string             `json:"position_id"`
	RefPositionID          pgtype.Text        `json:"ref_position_id"`
	TradingAcct            string             `json:"trading_acct"`
	ClientID               string             `json:"client_id"`
	Product                string             `json:"product"`
	Exchange               string             `json:"exchange"`
	Instrument             string             `json:"instrument"`
	Side                   pgtype.Text        `json:"side"`
	Status                 pgtype.Text        `json:"status"`
	PositionType           pgtype.Text        `json:"position_type"`
	SettlementStatus       pgtype.Text        `json:"settlement_status"`
	CalcType               pgtype.Text        `json:"calc_type"`
	OpenQty                pgtype.Numeric     `json:"open_qty"`
	OpenPx                 pgtype.Numeric     `json:"open_px"`
	ClosedQty              pgtype.Numeric     `json:"closed_qty"`
	ClosedPx               pgtype.Numeric     `json:"closed_px"`
	TradingCurr            pgtype.Text        `json:"trading_curr"`
	SettleCurr             pgtype.Text        `json:"settle_curr"`
	MarkPrice              pgtype.Numeric     `json:"mark_price"`
	MarkValue              pgtype.Numeric     `json:"mark_value"`
	ExchangeRate           pgtype.Numeric     `json:"exchange_rate"`
	UnrealizedPl           pgtype.Numeric     `json:"unrealized_pl"`
	RealizedPl             pgtype.Numeric     `json:"realized_pl"`
	MmAndCash              pgtype.Numeric     `json:"mm_and_cash"`
	CollateralHaircutRatio pgtype.Numeric     `json:"collateral_haircut_ratio"`
	CollateralHaircut      pgtype.Numeric     `json:"collateral_haircut"`
	OpenDate               pgtype.Timestamptz `json:"open_date"`
	ClosedDate             pgtype.Timestamptz `json:"closed_date"`
	CostToClose            pgtype.Numeric     `json:"cost_to_close"`
	TradeDate              pgtype.Date        `json:"trade_date"`
	TradingSessionID       pgtype.Text        `json:"trading_session_id"`
	Underlying             pgtype.Text        `json:"underlying"`
	OpenClose              pgtype.Text        `json:"open_close"`
	PutOrCall              pgtype.Text        `json:"put_or_call"`
	ContractSize           pgtype.Numeric     `json:"contract_size"`
	CreatedAt              time.Time          `json:"created_at"`
}
