// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Accountfilter struct {
	ClientID             pgtype.Text        `json:"client_id"`
	TradingAcct          string             `json:"trading_acct"`
	TraderID             pgtype.Text        `json:"trader_id"`
	CashBalanceBf        pgtype.Numeric     `json:"cash_balance_bf"`
	CashBalance          pgtype.Numeric     `json:"cash_balance"`
	EstTransCost         pgtype.Numeric     `json:"est_trans_cost"`
	EquityRealizedPl     pgtype.Numeric     `json:"equity_realized_pl"`
	EquityUnrealizedPl   pgtype.Numeric     `json:"equity_unrealized_pl"`
	MarginRealizedPl     pgtype.Numeric     `json:"margin_realized_pl"`
	MarginUnrealizedPl   pgtype.Numeric     `json:"margin_unrealized_pl"`
	EstClosingCost       pgtype.Numeric     `json:"est_closing_cost"`
	TransactionNotBooked pgtype.Numeric     `json:"transaction_not_booked"`
	EquityOrder          pgtype.Numeric     `json:"equity_order"`
	AccountValue         pgtype.Numeric     `json:"account_value"`
	DepositWithdraw      pgtype.Numeric     `json:"deposit_withdraw"`
	CollateralHaircut    pgtype.Numeric     `json:"collateral_haircut"`
	EquityPositionValue  pgtype.Numeric     `json:"equity_position_value"`
	MarginRequirement    pgtype.Numeric     `json:"margin_requirement"`
	Currency             pgtype.Text        `json:"currency"`
	BuyLimit             pgtype.Numeric     `json:"buy_limit"`
	SellLimit            pgtype.Numeric     `json:"sell_limit"`
	BuyExposure          pgtype.Numeric     `json:"buy_exposure"`
	SellExposure         pgtype.Numeric     `json:"sell_exposure"`
	LoanLimit            pgtype.Numeric     `json:"loan_limit"`
	NetLossLimit         pgtype.Numeric     `json:"net_loss_limit"`
	NetExposureLimit     pgtype.Numeric     `json:"net_exposure_limit"`
	MarginFactor         pgtype.Numeric     `json:"margin_factor"`
	AuthorizedOrderType  int64              `json:"authorized_order_type"`
	CalcMode             int32              `json:"calc_mode"`
	LimitMode            int32              `json:"limit_mode"`
	ActionMode           int32              `json:"action_mode"`
	NettingMode          int32              `json:"netting_mode"`
	MaxOrdQty            pgtype.Numeric     `json:"max_ord_qty"`
	MaxOrdVal            pgtype.Numeric     `json:"max_ord_val"`
	NoOfTransaction      int32              `json:"no_of_transaction"`
	TransactionInterval  int16              `json:"transaction_interval"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	CurrencyPair string             `json:"currency_pair"`
	Bid          pgtype.Numeric     `json:"bid"`
	Ask          pgtype.Numeric     `json:"ask"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Instrument struct {
	ProductCode       string             `json:"product_code"`
	ExchangeCode      string             `json:"exchange_code"`
	InstrumentCode    string             `json:"instrument_code"`
	UnderlyingCode    pgtype.Text        `json:"underlying_code"`
	InstrumentDesc    pgtype.Text        `json:"instrument_desc"`
	MaturityMonthyear pgtype.Text        `json:"maturity_monthyear"`
	MaturityDay       pgtype.Text        `json:"maturity_day"`
	PutOrCall         pgtype.Text        `json:"put_or_call"`
	StrikePrice       pgtype.Numeric     `json:"strike_price"`
	Symbol            pgtype.Text        `json:"symbol"`
	SymbolSfx         pgtype.Text        `json:"symbol_sfx"`
	Cusip             pgtype.Text        `json:"cusip"`
	Isin              pgtype.Text        `json:"isin"`
	Ric               pgtype.Text        `json:"ric"`
	Sedol             pgtype.Text        `json:"sedol"`
	Blpsyn            pgtype.Text        `json:"blpsyn"`
	Cficode           pgtype.Text        `json:"cficode"`
	PriceCode         pgtype.Text        `json:"price_code"`
	EffectiveDate     pgtype.Timestamp   `json:"effective_date"`
	Minqty            int32              `json:"minqty"`
	Sector            pgtype.Text        `json:"sector"`
	ContractSize      pgtype.Numeric     `json:"contract_size"`
	CorporateAction   pgtype.Text        `json:"corporate_action"`
	TradingSessionID  pgtype.Text        `json:"trading_session_id"`
	TradingCurr       pgtype.Text        `json:"trading_curr"`
	PriceDec          pgtype.Numeric     `json:"price_dec"`
	HandlInst         pgtype.Text        `json:"handl_inst"`
	TickID            int32              `json:"tick_id"`
	MarketSlippage    pgtype.Numeric     `json:"market_slippage"`
	RefPx             pgtype.Numeric     `json:"ref_px"`
	RefPxType         int16              `json:"ref_px_type"`
	Tplusone          pgtype.Int4        `json:"tplusone"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Instrumentfilter struct {
	ProductCode         string             `json:"product_code"`
	ExchangeCode        string             `json:"exchange_code"`
	InstrumentCode      string             `json:"instrument_code"`
	UnderlyingCode      pgtype.Text        `json:"underlying_code"`
	FilterOption        int32              `json:"filter_option"`
	MaxOrderQty         pgtype.Numeric     `json:"max_order_qty"`
	MaxOrderPrice       pgtype.Numeric     `json:"max_order_price"`
	MaxOrderValue       pgtype.Numeric     `json:"max_order_value"`
	BuyLimit            pgtype.Numeric     `json:"buy_limit"`
	SellLimit           pgtype.Numeric     `json:"sell_limit"`
	ExposureFactor      pgtype.Numeric     `json:"exposure_factor"`
	BuyExposure         pgtype.Numeric     `json:"buy_exposure"`
	SellExposure        pgtype.Numeric     `json:"sell_exposure"`
	BuyQtyLimit         pgtype.Numeric     `json:"buy_qty_limit"`
	BuyQtyExposure      pgtype.Numeric     `json:"buy_qty_exposure"`
	SellQtyLimit        pgtype.Numeric     `json:"sell_qty_limit"`
	SellQtyExposure     pgtype.Numeric     `json:"sell_qty_exposure"`
	NetQtyLimit         pgtype.Numeric     `json:"net_qty_limit"`
	NetQtyExposure      pgtype.Numeric     `json:"net_qty_exposure"`
	MarginType          int32              `json:"margin_type"`
	InitialMargin       pgtype.Numeric     `json:"Initial_margin"`
	MaintenanceMargin   pgtype.Numeric     `json:"Maintenance_margin"`
	MarginableRatio     pgtype.Numeric     `json:"marginable_ratio"`
	MarginCurr          pgtype.Text        `json:"margin_curr"`
	CommissionType      int32              `json:"commission_type"`
	Commission          pgtype.Numeric     `json:"commission"`
	MinCommission       pgtype.Numeric     `json:"min_commission"`
	CommissionCurr      pgtype.Text        `json:"commission_curr"`
	AuthorizedOrderType int64              `json:"authorized_order_type"`
	TradingCurr         pgtype.Text        `json:"trading_curr"`
	PriceCode           pgtype.Text        `json:"price_code"`
	RefPx               pgtype.Numeric     `json:"ref_px"`
	RefPxType           int16              `json:"ref_px_type"`
	ContractSize        pgtype.Numeric     `json:"contract_size"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	OrderID          string             `json:"order_id"`
	ClientID         string             `json:"client_id"`
	TradingAcct      string             `json:"trading_acct"`
	ProductCode      string             `json:"product_code"`
	ExchangeCode     string             `json:"exchange_code"`
	InstrumentCode   string             `json:"instrument_code"`
	OrderSide        int32              `json:"order_side"`
	OrderStatus      int32              `json:"order_status"`
	OrderType        int32              `json:"order_type"`
	OrderQty         pgtype.Numeric     `json:"order_qty"`
	OrderPrice       pgtype.Numeric     `json:"order_price"`
	TimeInforce      pgtype.Int4        `json:"time_inforce"`
	TradingSessionID pgtype.Text        `json:"trading_session_id"`
	ExpireDate       pgtype.Date        `json:"expire_date"`
	ExecQty          pgtype.Numeric     `json:"exec_qty"`
	ExecPrice        pgtype.Numeric     `json:"exec_price"`
	Cash             pgtype.Numeric     `json:"cash"`
	InitialMargin    pgtype.Numeric     `json:"Initial_margin"`
	Exposure         pgtype.Numeric     `json:"exposure"`
	EstCostToClose   pgtype.Numeric     `json:"est_cost_to_close"`
	OrderTime        pgtype.Timestamptz `json:"order_time"`
	UnderlyingCode   pgtype.Text        `json:"underlying_code"`
	OpenClose        int32              `json:"open_close"`
	PutOrCall        pgtype.Int4        `json:"put_or_call"`
	ContractSize     pgtype.Numeric     `json:"contract_size"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Position struct {
	PositionID             string             `json:"position_id"`
	RefPositionID          pgtype.Text        `json:"ref_position_id"`
	TradingAcct            string             `json:"trading_acct"`
	ClientID               string             `json:"client_id"`
	ProductCode            string             `json:"product_code"`
	ExchangeCode           string             `json:"exchange_code"`
	InstrumentCode         string             `json:"instrument_code"`
	PositionSide           int32              `json:"position_side"`
	PositionStatus         int32              `json:"position_status"`
	PositionType           int32              `json:"position_type"`
	SettlementStatus       int32              `json:"settlement_status"`
	CalcType               int32              `json:"calc_type"`
	OpenQty                pgtype.Numeric     `json:"open_qty"`
	OpenPx                 pgtype.Numeric     `json:"open_px"`
	ClosedQty              pgtype.Numeric     `json:"closed_qty"`
	ClosedPx               pgtype.Numeric     `json:"closed_px"`
	TradingCurr            string             `json:"trading_curr"`
	SettleCurr             string             `json:"settle_curr"`
	MarkPrice              pgtype.Numeric     `json:"mark_price"`
	MarkValue              pgtype.Numeric     `json:"mark_value"`
	ExchangeRate           pgtype.Numeric     `json:"exchange_rate"`
	UnrealizedPl           pgtype.Numeric     `json:"unrealized_pl"`
	RealizedPl             pgtype.Numeric     `json:"realized_pl"`
	MmAndCash              pgtype.Numeric     `json:"mm_and_cash"`
	CollateralHaircutRatio pgtype.Numeric     `json:"collateral_haircut_ratio"`
	CollateralHaircut      pgtype.Numeric     `json:"collateral_haircut"`
	OpenDate               pgtype.Timestamptz `json:"open_date"`
	ClosedDate             pgtype.Timestamptz `json:"closed_date"`
	CostToClose            pgtype.Numeric     `json:"cost_to_close"`
	TradeDate              pgtype.Date        `json:"trade_date"`
	TradingSessionID       pgtype.Text        `json:"trading_session_id"`
	UnderlyingCode         pgtype.Text        `json:"underlying_code"`
	OpenClose              int32              `json:"open_close"`
	PutOrCall              pgtype.Int4        `json:"put_or_call"`
	ContractSize           pgtype.Numeric     `json:"contract_size"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}
