// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accountfilter, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (Instrument, error)
	CreateInstrumentfilter(ctx context.Context, arg CreateInstrumentfilterParams) (Instrumentfilter, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	DeleteAccount(ctx context.Context, tradingAcct string) error
	DeleteCurrency(ctx context.Context, currencyPair string) error
	DeleteInstrument(ctx context.Context, arg DeleteInstrumentParams) error
	DeleteInstrumentfilter(ctx context.Context, arg DeleteInstrumentfilterParams) error
	DeleteOrder(ctx context.Context, orderID string) error
	DeletePosition(ctx context.Context, positionID string) error
	GetAccount(ctx context.Context, arg GetAccountParams) (Accountfilter, error)
	GetAccountForUpdate(ctx context.Context, arg GetAccountForUpdateParams) (Accountfilter, error)
	GetCurrency(ctx context.Context, currencyPair string) (Currency, error)
	GetCurrencyForUpdate(ctx context.Context, currencyPair string) (Currency, error)
	GetInstrument(ctx context.Context, arg GetInstrumentParams) (Instrument, error)
	GetInstrumentForUpdate(ctx context.Context, arg GetInstrumentForUpdateParams) (Instrument, error)
	GetInstrumentfilter(ctx context.Context, arg GetInstrumentfilterParams) (Instrumentfilter, error)
	GetInstrumentfilterForUpdate(ctx context.Context, arg GetInstrumentfilterForUpdateParams) (Instrumentfilter, error)
	GetOrder(ctx context.Context, orderID string) (Order, error)
	GetOrderForUpdate(ctx context.Context, orderID string) (Order, error)
	GetPosition(ctx context.Context, positionID string) (Position, error)
	GetPositionForUpdate(ctx context.Context, positionID string) (Position, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Accountfilter, error)
	ListCurrency(ctx context.Context, arg ListCurrencyParams) ([]Currency, error)
	ListInstrumentfilter(ctx context.Context, arg ListInstrumentfilterParams) ([]Instrumentfilter, error)
	ListInstruments(ctx context.Context, arg ListInstrumentsParams) ([]Instrument, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListPositions(ctx context.Context, arg ListPositionsParams) ([]Position, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accountfilter, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateInstrument(ctx context.Context, arg UpdateInstrumentParams) (Instrument, error)
	UpdateInstrumentfilter(ctx context.Context, arg UpdateInstrumentfilterParams) (Instrumentfilter, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
}

var _ Querier = (*Queries)(nil)
